"""Add structured_rules table

Revision ID: 21f78432f508
Revises: d9622f0a1e5b
Create Date: 2025-12-23 16:34:11.983842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f78432f508'
down_revision: Union[str, Sequence[str], None] = 'd9622f0a1e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structured_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('applicability_conditions', sa.JSON(), nullable=False),
    sa.Column('obligations', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ruleseverity'), nullable=False),
    sa.Column('raw_ai_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_rules_id'), 'structured_rules', ['id'], unique=False)
    op.create_index(op.f('ix_structured_rules_rule_id'), 'structured_rules', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structured_rules_rule_id'), table_name='structured_rules')
    op.drop_index(op.f('ix_structured_rules_id'), table_name='structured_rules')
    op.drop_table('structured_rules')
    # ### end Alembic commands ###
