"""Add compliance_decisions table

Revision ID: d77281adb806
Revises: 21f78432f508
Create Date: 2025-12-23 16:36:01.096669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77281adb806'
down_revision: Union[str, Sequence[str], None] = '21f78432f508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'REQUIRES_REVIEW', name='decisionoutcome'), nullable=False),
    sa.Column('violated_rules', sa.JSON(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('rule_versions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_decisions_id'), 'compliance_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_decisions_workflow_id'), 'compliance_decisions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_decisions_workflow_id'), table_name='compliance_decisions')
    op.drop_index(op.f('ix_compliance_decisions_id'), table_name='compliance_decisions')
    op.drop_table('compliance_decisions')
    # ### end Alembic commands ###
