"""Initial migration

Revision ID: d9622f0a1e5b
Revises: 
Create Date: 2025-12-23 16:33:11.477800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9622f0a1e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('PRIVACY', 'SECURITY', 'OPERATIONAL', 'FINANCIAL', name='rulecategory'), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ruleseverity'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='rulestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_id'), 'compliance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_rules_rule_id'), 'compliance_rules', ['rule_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.Enum('CLAIM_PROCESSING', 'POLICY_ISSUANCE', 'DATA_ACCESS_REQUEST', 'APPROVAL_ESCALATION', name='workflowtype'), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_id'), 'workflow_events', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_events_workflow_id'), 'workflow_events', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_workflow_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_compliance_rules_rule_id'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
